version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "10010:10010"
    networks:
      - chat_network

  client1:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    networks:
      - chat_network
    links:
      - "server"
 
networks:
  chat_network:
